
#cyoa-step1:cyoa-step1.cpp
#	g++ -Werror -Wall -pedantic -std=c++98 -o cyoa-step1 cyoa-step1.cpp
cyoa-step2:cyoa-step2.cpp
	g++ -Werror -Wall -pedantic -std=c++98 -ggdb3 -o cyoa-step2 cyoa-step2.cpp
